language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

env:
  - GO111MODULE=on

addons:
  homebrew:
    packages:
    - fortune

script:
  //- ./pre-commit
  //- go test -cpu=1,2 -v -tags integration ./...
